### ISSUE TITLE
💖 Use @layer base to lower precedences

### ISSUE THREAD

**Issue by 1aron** [master-co/normal.css#2]
### Current

```css
a {
    cursor: pointer;
}
```

### Expected

```css
@layer base {
    a {
        cursor: pointer;
    }
}
```
